name: Deploy Sphinx Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx_rtd_theme myst-parser
          # Add any additional dependencies your docs need
          # pip install -r datamule/docs/requirements.txt

      - name: Clean and Build Documentation
        run: |
          cd txt2dataset/docs
          # More aggressive cleaning
          rm -rf build/
          rm -rf source/_build/
          rm -rf _build/
          git rm -rf --cached build/ || true
          git rm -rf --cached _build/ || true
          make clean
          make html
          ls -la
          ls -la build/ || true
          
      - name: Check Build Directory
        run: |
          pwd
          ls -la datamule/docs/build/html || true
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./datamule/docs/build/html
          force_orphan: true  # This ensures a fresh history
          enable_jekyll: false
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Deploy Sphinx documentation [skip ci]'
          full_commit_message: |
            Deploy Sphinx documentation
            
            Build from ${{ github.sha }}
            Triggered by ${{ github.event_name }}